---
apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
        name: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole
        env:
        - name: TZ
          value: "America/Chicago"
        - name: WEBPASSWORD
          value: "test"
        volumeMounts:
        - name: pihole-native-volume
          mountPath: /etc/pihole
        - name: pihole-dnsmasq-volume
          mountPath: /etc/dnsmasq.d
      volumes:
      - name: pihole-native-volume
        persistentVolumeClaim:
          claimName: pihole-native-volume-claim
      - name: pihole-dnsmasq-volume
        persistentVolumeClaim:
          claimName: pihole-dnsmasq-volume-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-native-volume-claim
  namespace: pihole
  labels:
    app: pihole
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq-volume-claim
  namespace: pihole
  labels:
    app: pihole
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi