---
apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
        name: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole
        env:
        - name: TZ
          value: "America/Chicago"
        - name: WEBPASSWORD
          value: "test"
        volumeMounts:
        - name: pihole-native-volume
          mountPath: /etc/pihole
        - name: pihole-dnsmasq-volume
          mountPath: /etc/dnsmasq.d
      volumes:
      - name: pihole-native-volume
        persistentVolumeClaim:
          claimName: pihole-native-volume-claim
      - name: pihole-dnsmasq-volume
        persistentVolumeClaim:
          claimName: pihole-dnsmasq-volume-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-native-volume-claim
  namespace: pihole
  labels:
    app: pihole
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq-volume-claim
  namespace: pihole
  labels:
    app: pihole
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: pihole
spec:
  # type: NodePort
  selector:
    app: pihole
  ports:
  - port: 8000
    # nodePort: 8000
    targetPort: 80
    name: pihole-admin
  - port: 53
    # nodePort: 53
    targetPort: 53
    protocol: TCP
    name: dns-tcp
  - port: 53
    # nodePort: 53
    targetPort: 53
    protocol: UDP
    name: dns-udp
  externalIPs:
    - 192.168.39.69
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: pihole-tcp
#   namespace: pihole
# spec:
#   type: LoadBalancer
#   selector:
#     app: pihole
#   ports:
#   - port: 8000
#     targetPort: 80
#     name: pihole-admin
#   - port: 53
#     targetPort: 53
#     protocol: TCP
#     name: dns-tcp
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: pihole-udp
#   namespace: pihole
# spec:
#   type: LoadBalancer
#   selector:
#     app: pihole
#   ports:
#   - port: 53
#     targetPort: 53
#     protocol: UDP
#     name: dns-udp